# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import motion_pb2 as motion__pb2


class MotionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MotionStreaming = channel.stream_stream(
                '/thesis.Motion/MotionStreaming',
                request_serializer=motion__pb2.MotionRequest.SerializeToString,
                response_deserializer=motion__pb2.MotionResponse.FromString,
                )


class MotionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MotionStreaming(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MotionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MotionStreaming': grpc.stream_stream_rpc_method_handler(
                    servicer.MotionStreaming,
                    request_deserializer=motion__pb2.MotionRequest.FromString,
                    response_serializer=motion__pb2.MotionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'thesis.Motion', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Motion(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MotionStreaming(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/thesis.Motion/MotionStreaming',
            motion__pb2.MotionRequest.SerializeToString,
            motion__pb2.MotionResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
