# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: motion.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='motion.proto',
  package='thesis',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cmotion.proto\x12\x06thesis\"T\n\x14\x46\x61\x63\x65RecognizeRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x14\n\x0ctitleRequest\x18\x02 \x01(\t\x12\x16\n\x0e\x63ontentRequest\x18\x03 \x01(\t\"\xa4\x01\n\x15\x46\x61\x63\x65RecognizeResponse\x12\x12\n\nactivityId\x18\x01 \x01(\t\x12\x34\n\x06result\x18\x02 \x01(\x0e\x32$.thesis.FaceRecognizeResponse.Result\"A\n\x06Result\x12\x12\n\x0eRESULT_SUCCESS\x10\x00\x12\x12\n\x0eRESULT_FAILURE\x10\x01\x12\x0f\n\x0bRESULT_DENY\x10\x02\"M\n\x12\x46\x61\x63\x65IndexesConfirm\x12%\n\x07userInf\x18\x01 \x01(\x0b\x32\x14.thesis.UserFormData\x12\x10\n\x08imageIds\x18\x02 \x03(\t\"<\n\x13\x46\x61\x63\x65IndexesResponse\x12\x12\n\nactivityId\x18\x01 \x01(\t\x12\x11\n\tisSuccess\x18\x02 \x01(\x08\"4\n\x0cUserFormData\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x14\n\x0cisFaceVerify\x18\x02 \x01(\x08\"N\n\x0cRequestImage\x12\x15\n\rexpectedLabel\x18\x01 \x01(\t\x12\x14\n\x0cimagePayload\x18\x02 \x01(\x0c\x12\x11\n\tisPingMsg\x18\x03 \x01(\x08\"S\n\x0eMotionResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\x08\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x12\x11\n\tisPongMsg\x18\x04 \x01(\x08\x32\x86\x03\n\x06Motion\x12\x43\n\x0fMotionStreaming\x12\x14.thesis.RequestImage\x1a\x16.thesis.MotionResponse(\x01\x30\x01\x12\x41\n\x13RegisterFaceIndexes\x12\x14.thesis.UserFormData\x1a\x14.thesis.UserFormData\x12L\n\x11UpdateFaceIndexes\x12\x1a.thesis.FaceIndexesConfirm\x1a\x1b.thesis.FaceIndexesResponse\x12J\n\x16\x46\x61\x63\x65RecognizeStreaming\x12\x14.thesis.RequestImage\x1a\x16.thesis.MotionResponse(\x01\x30\x01\x12Z\n\x1bRequireFaceRecognizeRequest\x12\x1c.thesis.FaceRecognizeRequest\x1a\x1d.thesis.FaceRecognizeResponseb\x06proto3'
)



_FACERECOGNIZERESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='thesis.FaceRecognizeResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RESULT_SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESULT_FAILURE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RESULT_DENY', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=210,
  serialized_end=275,
)
_sym_db.RegisterEnumDescriptor(_FACERECOGNIZERESPONSE_RESULT)


_FACERECOGNIZEREQUEST = _descriptor.Descriptor(
  name='FaceRecognizeRequest',
  full_name='thesis.FaceRecognizeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='thesis.FaceRecognizeRequest.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='titleRequest', full_name='thesis.FaceRecognizeRequest.titleRequest', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contentRequest', full_name='thesis.FaceRecognizeRequest.contentRequest', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=108,
)


_FACERECOGNIZERESPONSE = _descriptor.Descriptor(
  name='FaceRecognizeResponse',
  full_name='thesis.FaceRecognizeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='activityId', full_name='thesis.FaceRecognizeResponse.activityId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='thesis.FaceRecognizeResponse.result', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FACERECOGNIZERESPONSE_RESULT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=275,
)


_FACEINDEXESCONFIRM = _descriptor.Descriptor(
  name='FaceIndexesConfirm',
  full_name='thesis.FaceIndexesConfirm',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userInf', full_name='thesis.FaceIndexesConfirm.userInf', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imageIds', full_name='thesis.FaceIndexesConfirm.imageIds', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=354,
)


_FACEINDEXESRESPONSE = _descriptor.Descriptor(
  name='FaceIndexesResponse',
  full_name='thesis.FaceIndexesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='activityId', full_name='thesis.FaceIndexesResponse.activityId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isSuccess', full_name='thesis.FaceIndexesResponse.isSuccess', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=416,
)


_USERFORMDATA = _descriptor.Descriptor(
  name='UserFormData',
  full_name='thesis.UserFormData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='thesis.UserFormData.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isFaceVerify', full_name='thesis.UserFormData.isFaceVerify', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=470,
)


_REQUESTIMAGE = _descriptor.Descriptor(
  name='RequestImage',
  full_name='thesis.RequestImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='expectedLabel', full_name='thesis.RequestImage.expectedLabel', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='imagePayload', full_name='thesis.RequestImage.imagePayload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isPingMsg', full_name='thesis.RequestImage.isPingMsg', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=472,
  serialized_end=550,
)


_MOTIONRESPONSE = _descriptor.Descriptor(
  name='MotionResponse',
  full_name='thesis.MotionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='thesis.MotionResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='thesis.MotionResponse.result', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='thesis.MotionResponse.confidence', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='isPongMsg', full_name='thesis.MotionResponse.isPongMsg', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=552,
  serialized_end=635,
)

_FACERECOGNIZERESPONSE.fields_by_name['result'].enum_type = _FACERECOGNIZERESPONSE_RESULT
_FACERECOGNIZERESPONSE_RESULT.containing_type = _FACERECOGNIZERESPONSE
_FACEINDEXESCONFIRM.fields_by_name['userInf'].message_type = _USERFORMDATA
DESCRIPTOR.message_types_by_name['FaceRecognizeRequest'] = _FACERECOGNIZEREQUEST
DESCRIPTOR.message_types_by_name['FaceRecognizeResponse'] = _FACERECOGNIZERESPONSE
DESCRIPTOR.message_types_by_name['FaceIndexesConfirm'] = _FACEINDEXESCONFIRM
DESCRIPTOR.message_types_by_name['FaceIndexesResponse'] = _FACEINDEXESRESPONSE
DESCRIPTOR.message_types_by_name['UserFormData'] = _USERFORMDATA
DESCRIPTOR.message_types_by_name['RequestImage'] = _REQUESTIMAGE
DESCRIPTOR.message_types_by_name['MotionResponse'] = _MOTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FaceRecognizeRequest = _reflection.GeneratedProtocolMessageType('FaceRecognizeRequest', (_message.Message,), {
  'DESCRIPTOR' : _FACERECOGNIZEREQUEST,
  '__module__' : 'motion_pb2'
  # @@protoc_insertion_point(class_scope:thesis.FaceRecognizeRequest)
  })
_sym_db.RegisterMessage(FaceRecognizeRequest)

FaceRecognizeResponse = _reflection.GeneratedProtocolMessageType('FaceRecognizeResponse', (_message.Message,), {
  'DESCRIPTOR' : _FACERECOGNIZERESPONSE,
  '__module__' : 'motion_pb2'
  # @@protoc_insertion_point(class_scope:thesis.FaceRecognizeResponse)
  })
_sym_db.RegisterMessage(FaceRecognizeResponse)

FaceIndexesConfirm = _reflection.GeneratedProtocolMessageType('FaceIndexesConfirm', (_message.Message,), {
  'DESCRIPTOR' : _FACEINDEXESCONFIRM,
  '__module__' : 'motion_pb2'
  # @@protoc_insertion_point(class_scope:thesis.FaceIndexesConfirm)
  })
_sym_db.RegisterMessage(FaceIndexesConfirm)

FaceIndexesResponse = _reflection.GeneratedProtocolMessageType('FaceIndexesResponse', (_message.Message,), {
  'DESCRIPTOR' : _FACEINDEXESRESPONSE,
  '__module__' : 'motion_pb2'
  # @@protoc_insertion_point(class_scope:thesis.FaceIndexesResponse)
  })
_sym_db.RegisterMessage(FaceIndexesResponse)

UserFormData = _reflection.GeneratedProtocolMessageType('UserFormData', (_message.Message,), {
  'DESCRIPTOR' : _USERFORMDATA,
  '__module__' : 'motion_pb2'
  # @@protoc_insertion_point(class_scope:thesis.UserFormData)
  })
_sym_db.RegisterMessage(UserFormData)

RequestImage = _reflection.GeneratedProtocolMessageType('RequestImage', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTIMAGE,
  '__module__' : 'motion_pb2'
  # @@protoc_insertion_point(class_scope:thesis.RequestImage)
  })
_sym_db.RegisterMessage(RequestImage)

MotionResponse = _reflection.GeneratedProtocolMessageType('MotionResponse', (_message.Message,), {
  'DESCRIPTOR' : _MOTIONRESPONSE,
  '__module__' : 'motion_pb2'
  # @@protoc_insertion_point(class_scope:thesis.MotionResponse)
  })
_sym_db.RegisterMessage(MotionResponse)



_MOTION = _descriptor.ServiceDescriptor(
  name='Motion',
  full_name='thesis.Motion',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=638,
  serialized_end=1028,
  methods=[
  _descriptor.MethodDescriptor(
    name='MotionStreaming',
    full_name='thesis.Motion.MotionStreaming',
    index=0,
    containing_service=None,
    input_type=_REQUESTIMAGE,
    output_type=_MOTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RegisterFaceIndexes',
    full_name='thesis.Motion.RegisterFaceIndexes',
    index=1,
    containing_service=None,
    input_type=_USERFORMDATA,
    output_type=_USERFORMDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateFaceIndexes',
    full_name='thesis.Motion.UpdateFaceIndexes',
    index=2,
    containing_service=None,
    input_type=_FACEINDEXESCONFIRM,
    output_type=_FACEINDEXESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FaceRecognizeStreaming',
    full_name='thesis.Motion.FaceRecognizeStreaming',
    index=3,
    containing_service=None,
    input_type=_REQUESTIMAGE,
    output_type=_MOTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RequireFaceRecognizeRequest',
    full_name='thesis.Motion.RequireFaceRecognizeRequest',
    index=4,
    containing_service=None,
    input_type=_FACERECOGNIZEREQUEST,
    output_type=_FACERECOGNIZERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MOTION)

DESCRIPTOR.services_by_name['Motion'] = _MOTION

# @@protoc_insertion_point(module_scope)
