# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: motion.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='motion.proto',
  package='thesis',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cmotion.proto\x12\x06thesis\"E\n\rMotionRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x15\n\rexpectedLabel\x18\x02 \x01(\t\x12\r\n\x05\x66rame\x18\x03 \x01(\x0c\" \n\x0eMotionResponse\x12\x0e\n\x06result\x18\x01 \x01(\x08\x32N\n\x06Motion\x12\x44\n\x0fMotionStreaming\x12\x15.thesis.MotionRequest\x1a\x16.thesis.MotionResponse(\x01\x30\x01\x62\x06proto3'
)




_MOTIONREQUEST = _descriptor.Descriptor(
  name='MotionRequest',
  full_name='thesis.MotionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='userId', full_name='thesis.MotionRequest.userId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expectedLabel', full_name='thesis.MotionRequest.expectedLabel', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='frame', full_name='thesis.MotionRequest.frame', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=93,
)


_MOTIONRESPONSE = _descriptor.Descriptor(
  name='MotionResponse',
  full_name='thesis.MotionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='thesis.MotionResponse.result', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=127,
)

DESCRIPTOR.message_types_by_name['MotionRequest'] = _MOTIONREQUEST
DESCRIPTOR.message_types_by_name['MotionResponse'] = _MOTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MotionRequest = _reflection.GeneratedProtocolMessageType('MotionRequest', (_message.Message,), {
  'DESCRIPTOR' : _MOTIONREQUEST,
  '__module__' : 'motion_pb2'
  # @@protoc_insertion_point(class_scope:thesis.MotionRequest)
  })
_sym_db.RegisterMessage(MotionRequest)

MotionResponse = _reflection.GeneratedProtocolMessageType('MotionResponse', (_message.Message,), {
  'DESCRIPTOR' : _MOTIONRESPONSE,
  '__module__' : 'motion_pb2'
  # @@protoc_insertion_point(class_scope:thesis.MotionResponse)
  })
_sym_db.RegisterMessage(MotionResponse)



_MOTION = _descriptor.ServiceDescriptor(
  name='Motion',
  full_name='thesis.Motion',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=129,
  serialized_end=207,
  methods=[
  _descriptor.MethodDescriptor(
    name='MotionStreaming',
    full_name='thesis.Motion.MotionStreaming',
    index=0,
    containing_service=None,
    input_type=_MOTIONREQUEST,
    output_type=_MOTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MOTION)

DESCRIPTOR.services_by_name['Motion'] = _MOTION

# @@protoc_insertion_point(module_scope)
